[pyprland]
plugins = [
    "scratchpads"
]

[scratchpads.kitty]
unfocus = "hide"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true